-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hyttebok.Object exposing (Dummy(..), SchemaProxy(..), Trip(..))


type Dummy
    = Dummy


type SchemaProxy
    = SchemaProxy


type Trip
    = Trip
