-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hyttebok.ScalarCodecs exposing (LocalDate, Long, codecs)

import Hyttebok.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias LocalDate =
    Hyttebok.Scalar.LocalDate


type alias Long =
    Hyttebok.Scalar.Long


codecs : Hyttebok.Scalar.Codecs LocalDate Long
codecs =
    Hyttebok.Scalar.defineCodecs
        { codecLocalDate = defaultCodecs.codecLocalDate
        , codecLong = defaultCodecs.codecLong
        }
