-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hyttebok.Object.Trip exposing (endDate, id, photos, slug, startDate, text, title)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hyttebok.InputObject
import Hyttebok.Interface
import Hyttebok.Object
import Hyttebok.Scalar
import Hyttebok.ScalarCodecs
import Hyttebok.Union
import Json.Decode as Decode


endDate : SelectionSet Hyttebok.ScalarCodecs.LocalDate Hyttebok.Object.Trip
endDate =
    Object.selectionForField "ScalarCodecs.LocalDate" "endDate" [] (Hyttebok.ScalarCodecs.codecs |> Hyttebok.Scalar.unwrapCodecs |> .codecLocalDate |> .decoder)


id : SelectionSet Int Hyttebok.Object.Trip
id =
    Object.selectionForField "Int" "id" [] Decode.int


photos : SelectionSet String Hyttebok.Object.Trip
photos =
    Object.selectionForField "String" "photos" [] Decode.string


slug : SelectionSet String Hyttebok.Object.Trip
slug =
    Object.selectionForField "String" "slug" [] Decode.string


startDate : SelectionSet Hyttebok.ScalarCodecs.LocalDate Hyttebok.Object.Trip
startDate =
    Object.selectionForField "ScalarCodecs.LocalDate" "startDate" [] (Hyttebok.ScalarCodecs.codecs |> Hyttebok.Scalar.unwrapCodecs |> .codecLocalDate |> .decoder)


text : SelectionSet String Hyttebok.Object.Trip
text =
    Object.selectionForField "String" "text" [] Decode.string


title : SelectionSet String Hyttebok.Object.Trip
title =
    Object.selectionForField "String" "title" [] Decode.string
