# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - elm_frontend

jobs:
  - job: Backend
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          git remote add heroku https://heroku:$(heroku token)@git.heroku.com/hyttebok.git
          git subtree split --prefix backend -b heroku
          git push -f heroku heroku:master
          git branch -D heroku
        displayName: Push to Heroku

  - job: Frontend
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        submodules: true

      - task: Npm@1
        inputs:
          command: install
          workingDir: web

      - task: Npm@1
        inputs:
          command: custom
          workingDir: web
          customCommand: run build
