name: Hyttebok frontend build & deploy

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: Build
        working-directory: web
        run: |
          yarn install
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: web/build
  
  deploy:
    name: Deploy
    
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: web/build
          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
