name: Hyttebok functions deploy

on:
  push:
    branches:
      - master
    paths:
      - 'functions/**'

jobs:
  deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
