name: Hyttebok functions deploy

on:
  push:
    branches:
      - master
    paths:
      - 'functions/**'
      - '.github/workflows/functions.yml'

jobs:
  deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
